# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time.
name: Java CI with Maven

on:
  push:
    branches: [ "Int-Actions" ]
  pull_request:
    branches: [ "Int-Actions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Use the latest version available

      - name: Set up JDK 21
        uses: actions/setup-java@v3  # Use the latest version available
        with:
          distribution: 'corretto'  # You can switch between 'temurin' or 'corretto'
          java-version: '21'
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4  # Ensure this is correctly set
        with:
          folder: target/docs/javadoc  # Ensure this path matches your javadoc output directory
          branch: gh-pages  # Optional: Specify the branch to deploy to
          clean: true       # Optional: Remove previous files from the branch

        env:
         ACTIONS_RUNNER_DEBUG: true


